version: '3.9'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   container_name: app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #   ports:
  #     - ${APP_PORT}:${PORT}
  #   networks:
  #     - custom-network
  #   volumes:
  #     - ./logger:/app/logger
  #     - ./src:/app/src
  #     - ./node_modules:/app/node_modules

  # postgres:
  #   build:
  #     context: ./db
  #     dockerfile: ./Dockerfile
  #   restart: unless-stopped
  #   container_name: postgres
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_USER:${POSTGRES_USER}
  #     - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
  #     - POSTGRES_DB:${POSTGRES_DB}
  #     - PGDATA:${PGDATA}
  #   ports:
  #     - ${POSTGRES_PORT}:${POSTGRES_DEFAULT_PORT}
  #   networks:
  #     - custom-network
  #   volumes:
  #     - ./pg_data:${PGDATA}
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - 'mongodb-data:/data/db'
    networks:
      - custom-network
    ports:
      - '27017:27017'
    healthcheck:
      test: 'echo ''db.runCommand("ping").ok'' | mongo 10.10.10.60:27017/test --quiet'
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - custom-network
    ports:
      - '8081:8081'
    healthcheck:
      test: wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  custom-network:
    name: custom-network
    driver: bridge

volumes:
  pgdata:
    driver: local
  mongodb-data:
    name: mongodb-data
